version: '3.9'

services:
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
        - orbfin.tech_backend

  orb_api:
    container_name: orb_api
    build: ./java
    environment:
      DATABASE_URL: jdbc:postgresql://java_db:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - java_db
    ports:
      - 8080:8080
    networks:
      - orbfin.tech_backend

  nginx:
    container_name: api.orbfin.development
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
    ports:
      - 443:443
    networks:
      - orbfin.tech_backend

networks:
  orbfin.tech_backend:
    external: true
    name: orbfin.tech_backend
  
volumes:
  pgdata: {}