version: '3.9'

services:
  pgsql-db:
    container_name: pgsql-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - orbfin.tech_backend

  orb-accounts:
    container_name: orb-accounts
    build:
      context: ./java
      dockerfile: orb-accounts.Dockerfile
    env_file:
    - .env
    depends_on:
      - pgsql-db
    networks:
      - orbfin.tech_backend

  nginx:
    container_name: api.orbfin.development
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
    ports:
      - 8080:80
      - 9443:9443
    networks:
      - orbfin.tech_backend

networks:
  orbfin.tech_backend:
    name: orbfin.tech_backend
  

volumes:
  pgdata: {}