version: '3.9'

services:
  pgsql-db:
    container_name: pgsql-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api.orbfin.tech
      # - the7ofdiamonds.tech_sites

  orb-login:
    env_file:
      - ./.env
    container_name: orb-login
    restart: always
    build:
      context: ./java/orb-login
      dockerfile: orb-login.Dockerfile
    volumes:
      - ./java/orb-login/login/target:/app
    networks:
      - api.orbfin.tech

  orb-accounts:
    container_name: orb-accounts
    restart: always
    build:
      context: ./java/orb-accounts
      dockerfile: orb-accounts.Dockerfile
    env_file:
    - .env
    depends_on:
      - pgsql-db
    volumes:
    - ./java/orb-accounts/accounts/target:/app
    networks:
      - api.orbfin.tech

  orb-finance:
    container_name: orb-finance
    restart: always
    build:
      context: ./java/orb-finance
      dockerfile: orb-finance.Dockerfile
    env_file:
    - .env
    depends_on:
      - pgsql-db
    volumes:
    - ./java/orb-finance/finance/target:/app
    networks:
      - api.orbfin.tech
      
  nginx:
    container_name: api.orbfin.development
    restart: always
    build:
      context: ./nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
    ports:
      - 8080:80
      - 443:443
    networks:
      - api.orbfin.tech
    
  redis:
    container_name: redis-session
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - api.orbfin.tech
      
networks:
  api.orbfin.tech:
    name: api.orbfin.tech
  
  # the7ofdiamonds.tech_sites:
  #   name: the7ofdiamonds.tech_sites
  #   external: true
    
volumes:
  pgdata: {}