services:
  pgsql-db:
    container_name: pgsql-db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - j.c.lyons_enterprises
      - seven_tech
      - orb

  # redis-session:
  #   container_name: redis-session
  #   image: "redis/redis-stack:edge"
  #   restart: always
  #   volumes:
  #     - ./redis/data:/data
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - orb

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - ./zookeeper:/data
    ports:
      - "2181:2181"
    networks:
      - orb

  kafka:
    container_name: kafka
    image: bitnami/kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka:/kafka
    ports:
      - "9094:9094"
    networks:
      - orb

  gateway:
    hostname: orb-gateway
    container_name: gateway
    image: orb-gateway:latest
    restart: always
    depends_on:
      - kafka
    env_file:
      - ./.env
    networks:
      - j.c.lyons_enterprises
      - seven_tech
      - orb


  communications:
    hostname: orb-communications
    container_name: communications
    image: orb-communications:latest
    restart: always
    depends_on:
      - kafka
    env_file:
      - .env
    networks:
      - j.c.lyons_enterprises
      - seven_tech
      - orb

  # accounts:
  #   hostname: orb-accounts
  #   container_name: accounts
  #   image: orb-accounts:latest
  #   restart: always
  #   depends_on:
  #     - pgsql-db
  #   env_file:
  #   - .env
  #   networks:
  #     - orb

  products-services:
    hostname: orb-products-services
    container_name: products-services
    image: orb-products-services:latest
    restart: always
    depends_on:
      - pgsql-db
      - kafka
    env_file:
      - .env
    networks:
      - orb

  # finance:
  #   hostname: orb-finance
  #   container_name: finance
  #   image: orb-finance:latest
  #   restart: always
  #   depends_on:
  #     - pgsql-db
  #   env_file:
  #     - .env
  #   networks:
  #     - api.orbfin.tech

  real-estate:
    hostname: orb-real-estate
    container_name: real-estate
    image: orb-real-estate:latest
    restart: always
    depends_on:
      - pgsql-db
    env_file:
      - .env
    networks:
      - j.c.lyons_enterprises
      - seven_tech
      - orb

  # investments:
  #   hostname: orb-investments
  #   container_name: investments
  #   image: orb-investments:latest
  #   restart: always
  #   depends_on:
  #     - pgsql-db
  #   env_file:
  #     - .env
  #   networks:
  #     - j.c.lyons_enterprises
  #     - seven_tech
  #     - orb

  # insurance:
  #   hostname: orb-insurance
  #   container_name: insurance
  #   image: orb-insurance:latest
  #   restart: always
  #   depends_on:
  #     - pgsql-db
  #   env_file:
  #     - .env
  #   networks:
  #     - j.c.lyons_enterprises
  #     - seven_tech
  #     - orb

  # server:
  #   hostname: api.orbfin.development
  #   container_name: api.orbfin.development
  #   image: nginx:latest
  #   restart: always
  #   depends_on:
  #     - gateway
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./nginx/templates/:/etc/nginx/templates
  #     - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
  #     - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
  #     - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
  #     - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
  #     - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
  #   ports:
  #     - ${BACK_PORT}:8080
  #     - ${BACK_PORT_SECURE}:8443
  #   networks:
  #     - j.c.lyons_enterprises
  #     - seven_tech
  #     - orb


networks:
  j.c.lyons_enterprises:
    name: j.c.lyons_enterprises
    external: true
  seven_tech:
    name: seven_tech
    external: true
  orb:
    name: orb
    external: true
      
volumes:
  zookeeper:
    driver: local
  kafka:
    driver: local
  pgdata: