services:
  pgsql-db:
    container_name: pgsql-db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - api.orbfin.tech

  redis:
    container_name: redis-session
    image: "redis/redis-stack:edge"
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    networks:
      - api.orbfin.tech

  zookeeper:
    container_name: zookeeper
    image: zookeeper
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    volumes:
      - ./zookeeper:/data
    ports:
      - "2181:2181"
    networks:
      - api.orbfin.tech

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka:/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - api.orbfin.tech

  # gateway:
  #   hostname: orb-gateway
  #   container_name: gateway
  #   image: orb-gateway:latest
  #   restart: always
  #   depends_on:
  #     - kafka
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - api.orbfin.tech
  #     - the7ofdiamonds.tech_sites

  communications:
    hostname: orb-communications
    container_name: communications
    image: orb-communications:latest
    restart: always
    depends_on:
      - kafka
    env_file:
      - .env
    ports:
      - 8087:8087
    networks:
      - api.orbfin.tech
      - the7ofdiamonds.tech_sites

  # accounts:
  #   hostname: orb-accounts
  #   container_name: accounts
  #   image: orb-accounts:latest
  #   restart: always
  #   depends_on:
  #     - pgsql-db
  #   env_file:
  #   - .env
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - api.orbfin.tech

  products-services:
    hostname: orb-products-services
    container_name: products-services
    image: orb-products-services:latest
    restart: always
    depends_on:
      - pgsql-db
      - kafka
    env_file:
      - .env
    ports:
      - 8082:8082
    networks:
      - api.orbfin.tech

  # finance:
  #   hostname: orb-finance
  #   container_name: finance
  #   image: orb-finance:latest
  #   restart: always
  #   depends_on:
  #     - pgsql-db
  #   env_file:
  #     - .env
  #   ports:
  #     - 8083:8083
  #   networks:
  #     - api.orbfin.tech

  # real-estate:
  #   hostname: orb-real-estate
  #   container_name: real-estate
  #   image: orb-real-estate:latest
  #   restart: always
  #   depends_on:
  #     - pgsql-db
  #   env_file:
  #     - .env
  #   ports:
  #     - 8084:8084
  #   networks:
  #     - api.orbfin.tech

  # investments:
  #   hostname: orb-investments
  #   container_name: investments
  #   image: orb-investments:latest
  #   restart: always
  #   depends_on:
  #     - pgsql-db
  #   env_file:
  #     - .env
  #   ports:
  #     - 8085:8085
  #   networks:
  #     - api.orbfin.tech

  # insurance:
  #   hostname: orb-insurance
  #   container_name: insurance
  #   image: orb-insurance:latest
  #   restart: always
  #   depends_on:
  #     - pgsql-db
  #   env_file:
  #     - .env
  #   ports:
  #     - 8086:8086
  #   networks:
  #     - api.orbfin.tech

  # server:
  #   container_name: api.orbfin.development
  #   image: nginx:latest
  #   restart: always
  #   depends_on:
  #     - gateway
  #   ports:
  #     - ${NGINX_PORT_ONE}:8000
  #     - ${NGINX_PORT_ONE_SECURE}:443
  #   volumes:
  #     - ./nginx/templates/:/etc/nginx/templates
  #     - ./nginx/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
  #     - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
  #     - ./nginx/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
  #     - ./nginx/snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
  #     - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
  #   networks:
  #     - api.orbfin.tech
  #   env_file: .env

networks:
  api.orbfin.tech:
    name: api.orbfin.tech
  the7ofdiamonds.tech_sites:
    name: the7ofdiamonds.tech_sites
    external: true
      
volumes:
  zookeeper:
    driver: local
  kafka:
    driver: local
  pgdata: