spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/orb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      show-sql: true
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    gateway:
      routes:
        - id: orb-authentication
          uri: http://localhost:8080
          predicates:
            - Path=/
            - Path=/signup/*
            - Path=/change-password
            - Path=/forgot-password
        - id: orb-accounts
          uri: ${ACCOUNTS_URI:http://localhost:8081}
          predicates:
            - Path=/accounts/**
          filters:
            - FilterAuth
            - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-products-services
          uri: ${PRODUCTS_SERVICES_URI:http://localhost:8082}
          predicates:
            - Path=/products-services/**
          filters:
            - FilterAuth
            - RewritePath=/products-services/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-finance
          uri: ${FINANCE_URI:http://localhost:8083}
          predicates:
            - Path=/finance/**
          filters:
            - FilterAuth
            - RewritePath=/finance/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-real-estate
          uri: ${REAL_ESTATE_URI:http://localhost:8084}
          predicates:
            - Path=/real-estate/**
          filters:
            - FilterAuth
            - RewritePath=/real-estate/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-investments
          uri: ${INVESTMENTS_URI:http://localhost:8085}
          predicates:
            - Path=/investments/**
          filters:
            - FilterAuth
            - RewritePath=/investments/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-insurance
          uri: ${INSURANCE_URI:http://localhost:8086}
          predicates:
            - Path=/insurance/**
          filters:
            - FilterAuth
            - RewritePath=/insurance/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
#    allow-circular-references: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 86400000  # a day

    oauth2:
      client:
        registration:
          gateway:
            provider:
              google:
                client-id: YOUR_GOOGLE_CLIENT_ID
                client-secret: YOUR_GOOGLE_CLIENT_SECRET
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

              microsoft:
                client-id: YOUR_MICROSOFT_CLIENT_ID
                client-secret: YOUR_MICROSOFT_CLIENT_SECRET
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

              apple:
                client-id: YOUR_APPLE_CLIENT_ID
                client-secret: YOUR_APPLE_CLIENT_SECRET
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

server:
  port: 8080

logging:
  level:
    org.springframework.security: trace
    web:
      server:
        authentication: debug
    org.springframework.cloud.gateway: DEBUG

    org.hibernate:
      SQL: DEBUG