spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/orb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # Change to "update" or "validate" for production
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Use full class name for Hibernate dialect

  cloud:
    gateway:
      routes:
        - id: orb-accounts
          uri: ${ACCOUNTS_URI:http://localhost:8081}
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-products-services
          uri: ${PRODUCTS_SERVICES_URI:http://localhost:8082}
          predicates:
            - Path=/products-services/**
          filters:
            - RewritePath=/products-services/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-finance
          uri: ${FINANCE_URI:http://localhost:8083}
          predicates:
            - Path=/finance/**
          filters:
            - RewritePath=/finance/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-real-estate
          uri: ${REAL_ESTATE_URI:http://localhost:8084}
          predicates:
            - Path=/real-estate/**
          filters:
            - RewritePath=/real-estate/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-investments
          uri: ${INVESTMENTS_URI:http://localhost:8085}
          predicates:
            - Path=/investments/**
          filters:
            - RewritePath=/investments/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader
        - id: orb-insurance
          uri: ${INSURANCE_URI:http://localhost:8086}
          predicates:
            - Path=/insurance/**
          filters:
            - RewritePath=/insurance/?(?<segment>.*), /$\{segment}
            - PreserveHostHeader

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 86400000  # a day

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
