package tech.orbfin.api.gateway.model.user;

public enum Authority {
    ADMIN_READ,
    ADMIN_UPDATE,
    ADMIN_DELETE,
    ADMIN_CREATE,
    MANAGER_READ,
    MANAGER_UPDATE,
    MANAGER_DELETE,
    MANAGER_CREATE,
    EDITOR_READ,
    EDITOR_UPDATE,
    EDITOR_DELETE,
    EDITOR_CREATE,
    CONTRIBUTOR_READ,
    CONTRIBUTOR_UPDATE,
    CONTRIBUTOR_CREATE,
    SUBSCRIBER_READ,
    USER_READ
}
